import Footer from "@/Components/Footer";
import Navbar from "@/Components/Navbar";
import "@/styles/globals.css";
import { store, persistedstore } from "../States/Store";
import { PersistGate } from "redux-persist/integration/react";
import { Provider } from "react-redux";
import { useEffect, useState } from "react";
import Lowerpanel from "@/Components/Lowerpanel";
import LoadingBar from "react-top-loading-bar";
import { useRouter } from "next/router";
import Head from "next/head";

export default function App({ Component, pageProps }) {
	const [prod, setprod] = useState({});
	const [progress, setprogress] = useState(0);
	const router = useRouter();

	useEffect(() => {
		router.events.on("routeChangeStart", () => {
			setprogress(50);
		});
		router.events.on("routeChangeComplete", () => {
			setprogress(100);
		});
	});

	const now = (item) => {
		setprod(item);
	};

	return (
		<>
			<Head>
				<title>Bongwear-Banglar Poridhan</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="icon.png" />
			</Head>
			<Provider store={store}>
				<PersistGate persistor={persistedstore}>
					<Navbar />
					<LoadingBar
						color="#8b008b"
						height={5}
						progress={progress}
						waitingTime={200}
					/>

					<Component {...pageProps} directBuy={now} itemTobuynow={prod} />

					<Footer />

					<Lowerpanel />
				</PersistGate>
			</Provider>
		</>
	);
}
