import React, { useRef, useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { Carousel } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Bongwear-Banglar Poridhan</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="icon.png" />
			</Head>

			<marquee behavior="scroll" direction="left" className="my-2">
				<div className="md:text-2xl w-[40rem] md:w-[60rem] h-16 items-center flex justify-center banner over rounded-lg text-white font-bold">
					<p className="">Welcome to Bongwear!!!!...বাংলার ঐতিহ্য , বাংলার সংস্কৃতি , বাংলার পরিধান</p>
				</div>
			</marquee>

			<div className="h-56  md:h-[32rem] my-15 ">
				<Carousel>
					<img src="ad1.jpg" className="" alt="..." />
					<img src="ad2.jpg" alt="..." />
					<img src="ad3.jpg" alt="..." />
				</Carousel>
			</div>
		</>
	);
}
